# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
np.__version__

'2.0.2'

2) Создать нулевой вектор размера 10

In [2]:
zeros_vector = np.zeros(10)
zeros_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [3]:
sevens_vector = np.full(7, 7)
sevens_vector

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
even_vector = np.arange(10, 101, 2)
even_vector

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [10]:
random_array = np.random.randint(0, 100, size=10)
reversed_array = random_array[::-1]
random_array, reversed_array

(array([92, 23, 44, 73, 66, 11, 67, 95, 78, 71]),
 array([71, 78, 95, 67, 11, 66, 73, 44, 23, 92]))

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [13]:
matrix_3x3 = np.arange(1, 10).reshape(3, 3)
matrix_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [15]:
matrix_4x4 = np.eye(4, k=1, dtype=int)
matrix_4x4

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [16]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [8]:
row = np.array([0, 1, 2, 3, 4])
matrix_5x5 = np.tile(row, (5, 1))
matrix_5x5

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [21]:
matrix = np.random.uniform(1, 10, (10, 10))
row_means = matrix.mean(axis=1)
normalized_matrix = matrix - row_means[:, np.newaxis]
normalized_matrix

array([[-2.60349578e+00, -4.31972866e+00,  3.45552189e+00,
         1.28397044e+00,  1.48094686e+00,  1.02558794e+00,
        -2.70741484e+00, -2.70907571e+00,  1.48231219e+00,
         3.61137567e+00],
       [ 8.14529389e-01, -1.80272685e-02,  6.04404460e-01,
        -1.51956174e+00,  2.80775497e-01, -1.43178452e+00,
         1.89633879e+00, -2.00240294e+00,  7.52558245e-01,
         6.23170084e-01],
       [-3.52712201e+00, -1.23578408e+00,  1.92015003e+00,
        -1.62350622e+00, -1.08907710e-01,  3.57496748e+00,
         9.18081755e-01, -3.29889072e-01, -8.53082318e-02,
         4.97318059e-01],
       [-2.55931975e+00, -6.79680196e-01,  2.61849289e+00,
        -1.21944421e+00,  1.91876109e+00,  2.70959701e+00,
        -2.29503889e+00, -3.14499527e-01, -2.64242383e+00,
         2.46355542e+00],
       [-1.44350568e+00,  4.16437111e+00,  3.89749414e+00,
        -2.13423199e+00,  3.66504238e-01, -3.16386756e-01,
        -1.61873348e+00, -4.70563851e-01, -2.04204186e+00,
        -4.

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [22]:
matrix = np.random.uniform(1, 10, (10, 10))
column_medians = np.median(matrix, axis=0)
normalized_matrix = matrix - column_medians
normalized_matrix

array([[-1.15358969, -0.52686694,  3.08372818, -2.48545717,  3.09787574,
        -1.02772994, -0.86592918, -0.13123221,  4.21615845, -2.73045652],
       [ 3.12645899,  0.50605061,  2.04329447,  0.01660483, -0.58212352,
         1.38421637,  2.42535351,  0.13123221,  4.17976188,  2.57556689],
       [-0.13242727, -5.77486764,  0.91221806, -2.28296815,  3.64378992,
        -0.80612532, -2.86098463,  2.90348625, -0.69142672, -0.0197971 ],
       [ 4.20602907,  2.34732901, -1.50237026, -4.40022773,  2.11939748,
        -2.63988113,  4.04338425, -1.56535001,  0.34387099,  0.161957  ],
       [ 6.17731261,  2.26379793, -0.95844938,  1.65518603, -4.10062486,
         1.45627751,  0.37715597,  0.67299573,  3.61040607, -2.51711508],
       [-0.71812292,  2.2972158 ,  1.02176682,  1.12122871, -3.18611153,
        -1.29705752, -1.13685273, -2.18876704, -1.04646212,  0.0197971 ],
       [-0.08699053, -0.50605061, -0.91221806, -3.72197991, -3.12188203,
         0.31766839, -2.95101281, -0.55849851

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [23]:
matrix = np.random.uniform(1, 10, (5, 5))
row_max = matrix.max(axis=1)
row_min = matrix.min(axis=1)
extended_matrix = np.column_stack((matrix, row_max, row_min))
extended_matrix

array([[8.47469883, 3.11353006, 7.23454907, 5.62872967, 3.18031903,
        8.47469883, 3.11353006],
       [3.1649538 , 8.38242082, 5.02634435, 8.24884977, 1.30886342,
        8.38242082, 1.30886342],
       [9.0476877 , 5.65753225, 8.64448071, 4.74298338, 8.14172659,
        9.0476877 , 4.74298338],
       [9.03461751, 3.09709406, 4.74424484, 1.11538445, 4.66334416,
        9.03461751, 1.11538445],
       [3.75285425, 9.47954231, 8.36639228, 6.13460712, 7.12481634,
        9.47954231, 3.75285425]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [7]:
import numpy as np

vec = np.arange(1, 52)

odd_vec = vec[vec % 2 != 0]
even_vec = vec[vec % 2 == 0]

n = min(len(odd_vec), len(even_vec))
odd_matrix = odd_vec[:n].reshape(n, 1)  
even_matrix = even_vec[:n].reshape(1, n)  

product_matrix = odd_matrix @ even_matrix  

try:
    inverse_matrix = np.linalg.inv(product_matrix)
    print("Обратная матрица:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матрица вырождена, обратная матрица не существует.")

Матрица вырождена, обратная матрица не существует.


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [32]:
import numpy as np

chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1  
chessboard[::2, 1::2] = 1  
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
